events {}

http {
  server {
    listen 80;

    location = /health {
      access_log off;
      return 200 "ok\n";
    }

    location /auth/ {
      proxy_pass http://user-service:8000/auth/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Cookie $http_cookie;
    }

    location /profiles/ {
      proxy_pass http://user-service:8000/profiles/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Cookie $http_cookie;
    }

    location /groups/ {
      auth_request /auth/validate;
      auth_request_set $user_id $upstream_http_x_user_id;
      proxy_pass http://group-service:4002;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Cookie $http_cookie;
      proxy_set_header X-User-Id $user_id;
       proxy_method $request_method;
    }

    location /expenses {
      auth_request /auth/validate;
      auth_request_set $user_id $upstream_http_x_user_id;
      proxy_pass http://expense-service:4003;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Cookie $http_cookie;
      proxy_set_header X-User-Id $user_id;
    }

    location = /auth/validate {
      internal;
      proxy_pass http://user-service:8000/auth/validate;
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";
      proxy_set_header Cookie $http_cookie;
    }
  }
}